import json
from typing import Any, Dict, List

import numpy as np


def load_npz(npz_path: str) -> Dict[str, Any]:
    """
    Loads data from a .npz file generated by generate_sliding_window_npz.
    """
    d = np.load(npz_path, allow_pickle=True)

    # Trajectories are stored as an array of JSON strings, parse them back.
    parsed_trajectories = [json.loads(t) for t in d["trajectories"]]

    # The scenario is saved as a numpy array, extract the string.
    scenario = d["scenario"].item() if d["scenario"].ndim == 0 else str(d["scenario"])

    return {
        "images": d["images"],
        "trajectories": parsed_trajectories,
        "window_info": d["window_info"],
        "scenario": scenario,
    }


def select_scenarios(scenarios: List[str], pack: Dict[str, Any]) -> Dict[str, Any]:
    # select scenarios from pack
    selected_indices = [i for i, sc in enumerate(pack["scenarios"]) if sc in scenarios]
    return {k: v[selected_indices] for k, v in pack.items()}
